const { chromium } = require('playwright');
(async () => {
  const browser = await chromium.launch();
  const page = await browser.newPage();
  page.on('request', request => console.log('REQ', request.method(), request.url()));
  page.on('response', response => console.log('RES', response.status(), response.url()));
  await page.goto('http://localhost:5180/Registro/Index');
  await page.fill('#Nombre', 'Akira');
  await page.fill('input[name="Apellido"]', 'Tanaka');
  await page.fill('.input-email', `jugador.${Date.now()}@correojugador.com`);
  await page.fill('[data-testid="input-password"]', 'Pass123!@');
  await page.fill('#Edad', '25');
  await page.fill('input[type="date"]', '1999-05-15');
  await page.fill('input[name="HoraPreferida"]', '20:00');
  await page.fill('textarea[name="Biografia"]', 'Jugador de prueba');
  await page.evaluate(() => document.querySelector('input[name="Genero"][value="Masculino"]')?.click());
  await page.selectOption('#selectPais', 'México');
  await page.selectOption('select[name="PlataformaFavorita"]', 'PC');
  await page.fill('[data-testid="slider-experiencia"]', '75');
  await page.fill('#colorFavorito', '#00F0FF');
  await page.setInputFiles('input[name="AvatarArchivo"]', 'data/images/avatar-sample.png');
  await page.evaluate(() => { const n = document.querySelector('#recibirNotificaciones'); if (n && !n.checked) n.click(); });
  await page.evaluate(() => { const s = document.querySelector('#sonidoActivado'); if (s && !s.checked) s.click(); });
  await page.evaluate(() => { const a = document.querySelector('#aceptaTerminos'); if (a && !a.checked) a.click(); });
  await page.click('.form-actions .btn--primary:last-child');
  await page.waitForURL(/\/Registro\/Confirmacion\//, { timeout: 20000 });
  console.log('DONE');
  await browser.close();
})();
